from . import help
from . import start
from . import btn_back
from . import admin
from . import check
from . import pulishlash
from . import balans
from . import pulyechish
from . import statistika
from . import reklama
from . import control_user
from . import mainsettings
from . import tolovtarix
from . import qollanma
from . import topuser
from . import sponsor